#!/bin/bash
# make a snapshot of __computer_name__'s root filesystem.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
unset bdrive host user target latest
# make sure we're running as root
if (( `id -u` != 0 )); then {
   echo "Sorry, must be root.  Exiting...";
   exit;
 } fi

source $DIR/src/route_arguments.sh
source $DIR/src/check_config.sh

if [ ! -d $bdrive ]; then
echo "Backup drive $bdrive does not exist.  Did you plug it in?"
exit 1
fi

if [ ! -d $bdrive/$latest ]; then
  echo "creating initial $host directory"
  mkdir $bdrive/$host
fi

# if [ ! -d $bdrive/$host/latest ]; then
#   echo "creating intial $host/latest directory"
#   mkdir $latest
# fi

source $DIR/src/backup.sh
